"""
50 predefined healthcare provider use cases with full architecture details.
Each case includes wizard answers, recommended architecture, scores, and spec.
"""

HEALTHCARE_CASES: list[dict] = [
    # --- 1-10: Clinical Operations ---
    {
        "id": "hc-001",
        "useCaseName": "Patient Intake Triage Assistant",
        "primaryGoal": "Automate patient intake forms and triage severity classification using clinical protocols",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-002",
        "useCaseName": "Radiology Report Summarizer",
        "primaryGoal": "Summarize radiology imaging reports into structured findings for referring physicians",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "finetune",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-003",
        "useCaseName": "Medication Interaction Checker",
        "primaryGoal": "Check prescribed medications against patient history for dangerous interactions",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-004",
        "useCaseName": "Nurse Shift Handoff Copilot",
        "primaryGoal": "Generate structured shift handoff reports from nursing notes and EHR data",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-005",
        "useCaseName": "Surgical Scheduling Optimizer",
        "primaryGoal": "Optimize OR scheduling by analyzing surgeon availability, equipment, and patient priority",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "workday"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-006",
        "useCaseName": "Clinical Trial Eligibility Screener",
        "primaryGoal": "Match patients to active clinical trials based on diagnosis, demographics, and lab values",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "finetune",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-007",
        "useCaseName": "Discharge Instruction Generator",
        "primaryGoal": "Auto-generate personalized discharge instructions at appropriate literacy level",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-008",
        "useCaseName": "Lab Results Interpreter",
        "primaryGoal": "Translate lab results into plain-language summaries with clinical significance flags",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-009",
        "useCaseName": "Pathology Slide Analysis Assistant",
        "primaryGoal": "Assist pathologists by pre-analyzing digital pathology slides and highlighting areas of concern",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "byom",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-010",
        "useCaseName": "Emergency Department Flow Manager",
        "primaryGoal": "Monitor ED patient flow and predict bottlenecks to optimize bed assignments",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    # --- 11-20: Revenue Cycle & Administration ---
    {
        "id": "hc-011",
        "useCaseName": "Prior Authorization Bot",
        "primaryGoal": "Automate prior authorization submissions to insurance payers with required clinical documentation",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-012",
        "useCaseName": "Claims Denial Analyzer",
        "primaryGoal": "Analyze denied insurance claims, identify root causes, and suggest appeal strategies",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-013",
        "useCaseName": "Medical Coding Assistant",
        "primaryGoal": "Suggest ICD-10 and CPT codes from clinical documentation to accelerate billing",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "finetune",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-014",
        "useCaseName": "Patient Payment Estimator",
        "primaryGoal": "Estimate out-of-pocket costs for patients based on insurance coverage and procedure codes",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
    },
    {
        "id": "hc-015",
        "useCaseName": "Revenue Leakage Detector",
        "primaryGoal": "Identify missed charges and under-coded procedures across hospital departments",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["azuresql", "fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-016",
        "useCaseName": "Insurance Eligibility Verifier",
        "primaryGoal": "Verify patient insurance eligibility in real-time during registration",
        "category": "Revenue Cycle",
        "complexity": "simple",
        "dataSources": ["external_api"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
    },
    {
        "id": "hc-017",
        "useCaseName": "Contract Rate Comparator",
        "primaryGoal": "Compare payer contract rates against Medicare benchmarks and flag underpayments",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-018",
        "useCaseName": "Accounts Receivable Follow-Up Agent",
        "primaryGoal": "Prioritize and automate follow-ups on aging accounts receivable by payer and amount",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "financial",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-019",
        "useCaseName": "Charge Capture Compliance Checker",
        "primaryGoal": "Validate charge capture against clinical documentation for compliance accuracy",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-020",
        "useCaseName": "Patient Collections Chatbot",
        "primaryGoal": "Engage patients via chat to set up payment plans and answer billing questions",
        "category": "Revenue Cycle",
        "complexity": "simple",
        "dataSources": ["azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "lowcode",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    # --- 21-30: Patient Engagement & Experience ---
    {
        "id": "hc-021",
        "useCaseName": "Appointment Scheduling Copilot",
        "primaryGoal": "Help patients schedule, reschedule, and manage appointments via natural language",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["azuresql"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-022",
        "useCaseName": "Chronic Disease Management Coach",
        "primaryGoal": "Provide personalized daily guidance for patients managing diabetes, hypertension, or COPD",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-023",
        "useCaseName": "Post-Surgical Recovery Monitor",
        "primaryGoal": "Monitor patient recovery via symptom check-ins and alert care teams on red flags",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "medium",
        "realtime": "yes",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-024",
        "useCaseName": "Patient Portal FAQ Bot",
        "primaryGoal": "Answer common patient questions about portal features, test results, and billing",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "lowcode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-025",
        "useCaseName": "Mental Health Check-In Agent",
        "primaryGoal": "Conduct structured mental health screening questionnaires and route to appropriate resources",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-026",
        "useCaseName": "Prescription Refill Assistant",
        "primaryGoal": "Process prescription refill requests and route to pharmacy or provider for approval",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-027",
        "useCaseName": "Health Literacy Translator",
        "primaryGoal": "Translate clinical documents into patient-friendly language at specified reading levels",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
    },
    {
        "id": "hc-028",
        "useCaseName": "Vaccination Reminder & Scheduler",
        "primaryGoal": "Send personalized vaccination reminders and enable self-scheduling for patients",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["azuresql"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "enterprise",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "no",
    },
    {
        "id": "hc-029",
        "useCaseName": "Symptom Checker Pre-Visit Agent",
        "primaryGoal": "Collect patient symptoms before visit and generate structured pre-visit summary for physician",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-030",
        "useCaseName": "Patient Satisfaction Survey Analyzer",
        "primaryGoal": "Analyze patient satisfaction surveys, identify themes, and generate department-level action plans",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["sharepoint", "fabric"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
    },
    # --- 31-40: Compliance & Quality ---
    {
        "id": "hc-031",
        "useCaseName": "HIPAA Compliance Auditor",
        "primaryGoal": "Continuously audit system access logs for potential HIPAA violations and alert compliance team",
        "category": "Compliance & Quality",
        "complexity": "complex",
        "dataSources": ["azuresql", "fabric"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-032",
        "useCaseName": "Clinical Documentation Improvement Agent",
        "primaryGoal": "Review physician notes for completeness and suggest documentation improvements for coding accuracy",
        "category": "Compliance & Quality",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "guided",
        "customModel": "finetune",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-033",
        "useCaseName": "Infection Control Surveillance Bot",
        "primaryGoal": "Monitor lab results and patient data for potential healthcare-associated infections",
        "category": "Compliance & Quality",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-034",
        "useCaseName": "Quality Metrics Dashboard Agent",
        "primaryGoal": "Generate quality measure reports (CMS Stars, HEDIS) and identify improvement opportunities",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
    },
    {
        "id": "hc-035",
        "useCaseName": "Adverse Event Reporting Assistant",
        "primaryGoal": "Guide staff through adverse event reporting and auto-populate safety reports",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-036",
        "useCaseName": "Regulatory Change Monitor",
        "primaryGoal": "Track CMS, FDA, and state regulatory changes and assess impact on hospital policies",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["external_api", "sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-037",
        "useCaseName": "Peer Review Coordinator",
        "primaryGoal": "Manage physician peer review workflows including case assignment, documentation, and tracking",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-038",
        "useCaseName": "Consent Form Manager",
        "primaryGoal": "Generate procedure-specific consent forms and track patient consent status",
        "category": "Compliance & Quality",
        "complexity": "simple",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "lowcode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-039",
        "useCaseName": "Medical Staff Credentialing Agent",
        "primaryGoal": "Automate physician credentialing verification and track expiring certifications",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-040",
        "useCaseName": "Mortality & Morbidity Review Prep",
        "primaryGoal": "Prepare M&M conference cases by pulling relevant clinical data and literature references",
        "category": "Compliance & Quality",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
    },
    # --- 41-50: Operations & Workforce ---
    {
        "id": "hc-041",
        "useCaseName": "Staff Scheduling Optimizer",
        "primaryGoal": "Optimize nursing and physician schedules based on patient census, skills, and labor rules",
        "category": "Operations & Workforce",
        "complexity": "complex",
        "dataSources": ["workday", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "hard",
    },
    {
        "id": "hc-042",
        "useCaseName": "Supply Chain Demand Forecaster",
        "primaryGoal": "Predict medical supply demand based on patient volume trends and seasonal patterns",
        "category": "Operations & Workforce",
        "complexity": "complex",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "finetune",
        "humanInLoop": "no",
    },
    {
        "id": "hc-043",
        "useCaseName": "Bed Management Real-Time Tracker",
        "primaryGoal": "Track bed availability across units in real-time and optimize patient placement",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "medium",
        "realtime": "yes",
        "teamSize": "medium",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-044",
        "useCaseName": "Employee Onboarding Health Guide",
        "primaryGoal": "Guide new healthcare employees through compliance training, certifications, and policy acknowledgments",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "no",
    },
    {
        "id": "hc-045",
        "useCaseName": "Equipment Maintenance Predictor",
        "primaryGoal": "Predict medical equipment maintenance needs based on usage patterns and manufacturer guidelines",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-046",
        "useCaseName": "Multi-Site Performance Comparator",
        "primaryGoal": "Compare operational KPIs across hospital sites and identify best practices for standardization",
        "category": "Operations & Workforce",
        "complexity": "complex",
        "dataSources": ["fabric", "snowflake"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
    },
    {
        "id": "hc-047",
        "useCaseName": "Physician Burnout Early Warning",
        "primaryGoal": "Analyze workload data and engagement signals to identify physicians at risk of burnout",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["workday", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-048",
        "useCaseName": "Multi-Agent Claims Processing Pipeline",
        "primaryGoal": "Coordinate intake, coding, submission, and follow-up agents for end-to-end claims processing",
        "category": "Operations & Workforce",
        "complexity": "multiagent",
        "dataSources": ["azuresql", "external_api", "fabric"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "multiagent",
        "customModel": "no",
        "humanInLoop": "escalation",
    },
    {
        "id": "hc-049",
        "useCaseName": "Patient Transport Coordinator",
        "primaryGoal": "Optimize intra-hospital patient transport by coordinating transport staff and elevator scheduling",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["azuresql"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "yes",
        "teamSize": "small",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
    },
    {
        "id": "hc-050",
        "useCaseName": "Clinical Research Data Harmonizer",
        "primaryGoal": "Harmonize clinical data from multiple EMR systems into standardized FHIR format for research",
        "category": "Operations & Workforce",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api", "snowflake"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "byom",
        "humanInLoop": "hard",
    },
]
