"""
50 predefined healthcare provider use cases with full architecture details.
Each case includes wizard answers, recommended architecture, scores, and spec.
Architecture distribution: ~13 Copilot Studio, ~12 Agent Builder, ~12 Fabric Agent, ~13 Foundry Agent.
Each case explains WHY that architecture was chosen and which alternative was considered.
"""

HEALTHCARE_CASES: list[dict] = [
    # === 1-10: Clinical Operations ===
    {
        "id": "hc-001",
        "useCaseName": "Patient Intake Triage Assistant",
        "primaryGoal": "Automate patient intake forms and triage severity classification using clinical protocols",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["azuresql", "sharepoint"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Requires PHI/HIPAA compliance for patient health data. Azure AI Foundry is mandatory when handling Protected Health Information to ensure BAA coverage and compliance controls.",
        "alternativeConsidered": "Copilot Studio could handle the guided workflow, but cannot meet HIPAA requirements for PHI data.",
    },
    {
        "id": "hc-002",
        "useCaseName": "Radiology Report Summarizer",
        "primaryGoal": "Summarize radiology imaging reports into structured findings for referring physicians",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "finetune",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Combines PHI data with a fine-tuned radiology language model. Only Azure AI Foundry supports both HIPAA compliance and custom model deployment.",
        "alternativeConsidered": "Fabric Agent has strong data capabilities but cannot host fine-tuned models or meet PHI compliance requirements.",
    },
    {
        "id": "hc-003",
        "useCaseName": "Medication Interaction Checker",
        "primaryGoal": "Check prescribed medications against patient history for dangerous interactions",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Patient medication history is PHI requiring HIPAA compliance. Real-time external API calls to drug databases need Foundry orchestration capabilities.",
        "alternativeConsidered": "Fabric Agent could handle the data analytics, but PHI hard-cap enforcement requires Azure AI Foundry.",
    },
    {
        "id": "hc-004",
        "useCaseName": "Nurse Shift Handoff Copilot",
        "primaryGoal": "Generate structured shift handoff summaries from departmental templates and scheduling data",
        "category": "Clinical Operations",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Simple Teams-based bot pulling from SharePoint templates. No PHI involved (uses de-identified departmental summaries). Low-code Copilot Studio is ideal for this straightforward workflow.",
        "alternativeConsidered": "Agent Builder could work via M365 Copilot, but Teams channel + low-code requirement makes Copilot Studio the better fit.",
    },
    {
        "id": "hc-005",
        "useCaseName": "Surgical Scheduling Optimizer",
        "primaryGoal": "Optimize OR scheduling by analyzing surgeon availability, equipment, and patient priority",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Autonomous agent handling patient surgical data (PHI). Complex multi-system orchestration with hard human approval gates requires Foundry full control plane.",
        "alternativeConsidered": "Fabric Agent could handle scheduling analytics but cannot operate autonomously with PHI data.",
    },
    {
        "id": "hc-006",
        "useCaseName": "Clinical Trial Eligibility Screener",
        "primaryGoal": "Match patients to active clinical trials based on diagnosis, demographics, and lab values",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "finetune",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Patient matching against trials requires PHI access plus a fine-tuned clinical NLP model. Only Foundry supports both HIPAA compliance and custom model hosting.",
        "alternativeConsidered": "Fabric Agent could analyze trial data at scale, but the fine-tuned model and PHI requirements mandate Foundry.",
    },
    {
        "id": "hc-007",
        "useCaseName": "Discharge Instruction Generator",
        "primaryGoal": "Generate personalized discharge instructions from hospital policy templates at appropriate literacy levels",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Uses SharePoint-grounded hospital policy templates via M365 Copilot. No PHI involved (templates are generic). Agent Builder declarative framework is perfect for document generation from enterprise knowledge.",
        "alternativeConsidered": "Copilot Studio could handle this, but the deep SharePoint grounding and M365 Copilot integration make Agent Builder more natural.",
    },
    {
        "id": "hc-008",
        "useCaseName": "Lab Results Trend Analyzer",
        "primaryGoal": "Analyze aggregated lab result trends across departments to identify quality patterns and outliers",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Aggregated lab data analytics across Fabric Lakehouse. Uses de-identified/PII-level data (not individual PHI). Fabric Agent excels at large-scale structured data analysis with OneLake.",
        "alternativeConsidered": "Foundry Agent has more flexibility, but the analytics-first nature of this use case and Fabric data source make Fabric Agent the optimal choice.",
    },
    {
        "id": "hc-009",
        "useCaseName": "Pathology Slide Analysis Assistant",
        "primaryGoal": "Assist pathologists by pre-analyzing digital pathology slides and highlighting areas of concern",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "byom",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Requires bring-your-own-model (custom pathology CV model) plus PHI compliance for patient slide data. Only Foundry supports BYOM deployment with HIPAA controls.",
        "alternativeConsidered": "No other architecture supports both custom model hosting and PHI compliance.",
    },
    {
        "id": "hc-010",
        "useCaseName": "Emergency Department Flow Dashboard",
        "primaryGoal": "Monitor ED operational flow metrics and predict bottlenecks using historical volume patterns",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Operational analytics dashboard using Fabric Lakehouse for historical ED volume data. Uses PII-level aggregate data (not individual patient PHI). Fabric Agent data pipeline integration is ideal.",
        "alternativeConsidered": "Foundry Agent could handle this but would be over-engineered for a read-only analytics dashboard without PHI.",
    },
    # === 11-20: Revenue Cycle & Administration ===
    {
        "id": "hc-011",
        "useCaseName": "Prior Authorization Bot",
        "primaryGoal": "Automate prior authorization submissions to insurance payers with required clinical documentation",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Autonomous agent submitting clinical documentation (PHI) to external payer APIs. PHI requirement plus autonomous behavior requires Foundry compliance and orchestration controls.",
        "alternativeConsidered": "Copilot Studio could handle simple form submissions, but the PHI data and autonomous external API calls require Foundry.",
    },
    {
        "id": "hc-012",
        "useCaseName": "Claims Denial Analyzer",
        "primaryGoal": "Analyze denied insurance claims patterns and suggest appeal strategies from policy documents",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "financial",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Analyzes denial patterns using SharePoint-stored policy documents via M365 Copilot. Financial data (not PHI). Agent Builder document grounding excels at policy analysis and recommendation.",
        "alternativeConsidered": "Fabric Agent could analyze denial data at scale, but the SharePoint policy grounding and M365 workflow make Agent Builder more suitable.",
    },
    {
        "id": "hc-013",
        "useCaseName": "Medical Coding Assistant",
        "primaryGoal": "Suggest ICD-10 and CPT codes from clinical documentation to accelerate billing",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "finetune",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Fine-tuned medical coding model processing clinical documentation (PHI). Both the custom model and PHI requirements mandate Azure AI Foundry.",
        "alternativeConsidered": "Agent Builder could assist with code lookup, but the fine-tuned model and PHI data require Foundry infrastructure.",
    },
    {
        "id": "hc-014",
        "useCaseName": "Patient Payment Estimator",
        "primaryGoal": "Estimate out-of-pocket costs for patients based on insurance coverage tables and procedure codes",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Reads insurance coverage tables from SharePoint and calculates estimates. No PHI (uses procedure codes, not patient data). Agent Builder with SharePoint grounding provides clean M365 integration.",
        "alternativeConsidered": "Copilot Studio could build a simple estimator, but the SharePoint coverage table grounding is better served by Agent Builder.",
    },
    {
        "id": "hc-015",
        "useCaseName": "Revenue Leakage Detector",
        "primaryGoal": "Identify missed charges and under-coded procedures across hospital departments using Fabric analytics",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Large-scale financial data analytics across Fabric Lakehouse to detect billing anomalies. Financial data (not PHI). Fabric Agent data pipeline and analytics capabilities are purpose-built for this.",
        "alternativeConsidered": "Foundry Agent could handle this, but the analytics-first pattern with Fabric data source makes Fabric Agent the natural choice.",
    },
    {
        "id": "hc-016",
        "useCaseName": "Insurance Eligibility Verifier",
        "primaryGoal": "Verify patient insurance eligibility in real-time during registration via Teams",
        "category": "Revenue Cycle",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Simple Teams bot for registration staff to verify eligibility. PII-level data only (name, DOB, insurance ID -- not health records). Copilot Studio low-code Teams bot is the fastest path to production.",
        "alternativeConsidered": "Agent Builder could work via M365 Copilot, but the Teams-first UX and simplicity make Copilot Studio more appropriate.",
    },
    {
        "id": "hc-017",
        "useCaseName": "Contract Rate Comparator",
        "primaryGoal": "Compare payer contract rates against Medicare benchmarks from SharePoint-stored rate sheets",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "financial",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Compares contract documents stored in SharePoint against Medicare rate tables. Financial data only. Agent Builder declarative document grounding excels at cross-document comparison.",
        "alternativeConsidered": "Fabric Agent could analyze rate data at scale, but the SharePoint document-centric workflow is better served by Agent Builder.",
    },
    {
        "id": "hc-018",
        "useCaseName": "Accounts Receivable Follow-Up Agent",
        "primaryGoal": "Prioritize and guide follow-ups on aging accounts receivable via Teams notifications",
        "category": "Revenue Cycle",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "financial",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Simple guided Teams bot for AR staff to manage follow-ups. Financial data only (account balances, not health records). Copilot Studio low-code Teams integration is ideal for this guided workflow.",
        "alternativeConsidered": "Agent Builder could extend M365 Copilot for this, but the Teams-first channel and simplicity favor Copilot Studio.",
    },
    {
        "id": "hc-019",
        "useCaseName": "Charge Capture Compliance Checker",
        "primaryGoal": "Validate charge capture accuracy against billing rules using Fabric data warehouse analytics",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Analytics-driven compliance checking across Fabric Lakehouse billing data. Financial data (not PHI). Fabric Agent data pipeline and rule engine capabilities are purpose-built for compliance analytics.",
        "alternativeConsidered": "Foundry Agent could handle complex compliance rules, but the Fabric data source and analytics pattern make Fabric Agent the better fit.",
    },
    {
        "id": "hc-020",
        "useCaseName": "Patient Collections Chatbot",
        "primaryGoal": "Engage patients via Teams chat to set up payment plans and answer billing questions",
        "category": "Revenue Cycle",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Simple conversational bot guiding patients through payment options. PII-level data only (name, account number -- not health records). Copilot Studio is ideal for this low-code Teams chatbot pattern.",
        "alternativeConsidered": "Foundry Agent would be overkill for a simple payment chatbot that does not require PHI access.",
    },
    # === 21-30: Patient Engagement & Experience ===
    {
        "id": "hc-021",
        "useCaseName": "Appointment Scheduling Copilot",
        "primaryGoal": "Help patients schedule, reschedule, and manage appointments via Teams natural language",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Simple appointment management via Teams natural language. PII only (patient name, appointment time -- not health data). Copilot Studio excels at this guided conversational pattern with Teams.",
        "alternativeConsidered": "Agent Builder could extend M365 Copilot for scheduling, but the Teams-first patient-facing UX makes Copilot Studio the better choice.",
    },
    {
        "id": "hc-022",
        "useCaseName": "Chronic Disease Management Coach",
        "primaryGoal": "Provide personalized daily guidance for patients managing diabetes, hypertension, or COPD",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Personalized health coaching requires access to patient medical records (PHI). Integration with external health device APIs needs Foundry orchestration and compliance controls.",
        "alternativeConsidered": "Copilot Studio could handle guided conversations, but PHI data access for personalized coaching requires Foundry.",
    },
    {
        "id": "hc-023",
        "useCaseName": "Post-Surgical Recovery Trends Monitor",
        "primaryGoal": "Analyze aggregated post-surgical recovery patterns across procedures to improve care protocols",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Aggregated recovery analytics across Fabric Lakehouse using de-identified patient cohorts (PII level, not individual PHI). Fabric Agent excels at population-level health analytics.",
        "alternativeConsidered": "Foundry Agent could provide deeper analysis, but the read-only analytics pattern with Fabric data makes Fabric Agent more efficient.",
    },
    {
        "id": "hc-024",
        "useCaseName": "Patient Portal FAQ Bot",
        "primaryGoal": "Answer common patient questions about portal features, test results navigation, and billing via Teams",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Simple FAQ bot answering general portal questions from SharePoint knowledge base. No patient data involved. Copilot Studio is the fastest way to deploy a Teams FAQ bot with SharePoint grounding.",
        "alternativeConsidered": "Agent Builder could also ground on SharePoint, but the simple Teams Q&A pattern is Copilot Studio sweet spot.",
    },
    {
        "id": "hc-025",
        "useCaseName": "Mental Health Screening Trends Analyzer",
        "primaryGoal": "Analyze population-level mental health screening trends to identify at-risk demographics and resource gaps",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Population-level mental health analytics using de-identified screening data in Fabric. PII-level aggregate data (not individual patient PHI). Fabric Agent data analysis capabilities are ideal.",
        "alternativeConsidered": "Foundry Agent could provide more complex analysis, but the read-only population analytics pattern does not justify Foundry overhead.",
    },
    {
        "id": "hc-026",
        "useCaseName": "Prescription Refill Assistant",
        "primaryGoal": "Process prescription refill requests via Teams and route to pharmacy for approval",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Simple Teams bot collecting refill requests (medication name, patient ID -- PII not PHI). Hard human approval gate ensures pharmacist review. Copilot Studio excels at guided workflows with approval routing.",
        "alternativeConsidered": "Foundry Agent would be needed if accessing patient medical records, but this workflow only handles refill requests (PII level).",
    },
    {
        "id": "hc-027",
        "useCaseName": "Health Literacy Translator",
        "primaryGoal": "Translate hospital policy documents into patient-friendly language at specified reading levels via M365 Copilot",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Translates SharePoint-stored hospital policies into plain language. No patient data involved. Agent Builder declarative framework with SharePoint grounding and M365 Copilot integration is purpose-built for this.",
        "alternativeConsidered": "Copilot Studio could handle document retrieval, but Agent Builder deep SharePoint grounding produces better document transformation results.",
    },
    {
        "id": "hc-028",
        "useCaseName": "Vaccination Reminder & Scheduler",
        "primaryGoal": "Send vaccination reminders and enable self-scheduling for patients via Teams notifications",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Simple notification and scheduling bot via Teams. PII only (patient name, vaccination dates -- not health records). Copilot Studio is ideal for this automated Teams notification pattern.",
        "alternativeConsidered": "Agent Builder could handle scheduling via M365, but the Teams notification-first pattern is a Copilot Studio strength.",
    },
    {
        "id": "hc-029",
        "useCaseName": "Symptom Checker Pre-Visit Agent",
        "primaryGoal": "Collect patient symptoms before visit via Teams and generate structured pre-visit summary",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Guided Teams chatbot collecting self-reported symptoms (PII, not clinical PHI since patient self-reports before diagnosis). Copilot Studio excels at this structured data collection via Teams.",
        "alternativeConsidered": "Foundry Agent would be needed if integrating with EHR systems for clinical data, but pre-visit symptom collection is PII-level.",
    },
    {
        "id": "hc-030",
        "useCaseName": "Patient Satisfaction Survey Analyzer",
        "primaryGoal": "Analyze patient satisfaction survey results and generate department-level improvement plans via M365 Copilot",
        "category": "Patient Engagement",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Analyzes survey data stored in SharePoint and generates action plans. No patient health data. Agent Builder M365 Copilot integration with SharePoint grounding is ideal for document analysis and reporting.",
        "alternativeConsidered": "Fabric Agent could handle larger-scale survey analytics, but the SharePoint-centric workflow and M365 integration favor Agent Builder.",
    },
    # === 31-40: Compliance & Quality ===
    {
        "id": "hc-031",
        "useCaseName": "HIPAA Compliance Audit Log Analyzer",
        "primaryGoal": "Analyze system access audit logs in Fabric to identify potential HIPAA violation patterns",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Audit log analytics across Fabric Lakehouse. Analyzes access patterns (PII -- user IDs, timestamps), not patient health records directly. Fabric Agent data pipeline capabilities are ideal for log analysis.",
        "alternativeConsidered": "Foundry Agent could provide deeper analysis, but the read-only audit log analytics pattern is well-served by Fabric Agent data capabilities.",
    },
    {
        "id": "hc-032",
        "useCaseName": "Clinical Documentation Improvement Agent",
        "primaryGoal": "Review physician notes for completeness and suggest documentation improvements for coding accuracy",
        "category": "Compliance & Quality",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "guided",
        "customModel": "finetune",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Reviews actual physician clinical notes (PHI) using a fine-tuned clinical NLP model. Both PHI compliance and custom model requirements mandate Azure AI Foundry.",
        "alternativeConsidered": "Agent Builder could assist with document improvement from templates, but the PHI data and fine-tuned model require Foundry.",
    },
    {
        "id": "hc-033",
        "useCaseName": "Infection Control Surveillance Bot",
        "primaryGoal": "Monitor lab results and patient data for potential healthcare-associated infections in real-time",
        "category": "Compliance & Quality",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Autonomous real-time surveillance of patient lab results (PHI). Complex multi-source integration with autonomous alerting requires Foundry full compliance and orchestration platform.",
        "alternativeConsidered": "Fabric Agent could analyze infection patterns in aggregate data, but real-time individual patient monitoring with PHI requires Foundry.",
    },
    {
        "id": "hc-034",
        "useCaseName": "Quality Metrics Dashboard Agent",
        "primaryGoal": "Generate CMS Stars and HEDIS quality measure reports from SharePoint data via M365 Copilot",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Generates quality reports from SharePoint-stored measure definitions and benchmarks. No patient data (uses aggregate metrics). Agent Builder M365 Copilot integration with SharePoint grounding is ideal for report generation.",
        "alternativeConsidered": "Fabric Agent could analyze quality data at scale, but the SharePoint document-centric reporting pattern favors Agent Builder.",
    },
    {
        "id": "hc-035",
        "useCaseName": "Adverse Event Reporting Assistant",
        "primaryGoal": "Guide staff through standardized adverse event reporting forms via Teams with approval routing",
        "category": "Compliance & Quality",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Simple guided Teams bot for standardized event reporting. No PHI (reports contain event descriptions, not patient health records). Copilot Studio excels at guided form workflows with hard approval gates.",
        "alternativeConsidered": "Agent Builder could handle this via M365, but the Teams-first guided workflow with hard approval routing is Copilot Studio core strength.",
    },
    {
        "id": "hc-036",
        "useCaseName": "Regulatory Change Monitor",
        "primaryGoal": "Track CMS, FDA, and state regulatory changes from monitored documents and assess policy impact via M365 Copilot",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Monitors regulatory documents in SharePoint and assesses impact via M365 Copilot. No patient data. Agent Builder document grounding and M365 integration are ideal for regulatory document monitoring.",
        "alternativeConsidered": "Copilot Studio could alert on changes, but Agent Builder deep document understanding and M365 Copilot integration provides better regulatory analysis.",
    },
    {
        "id": "hc-037",
        "useCaseName": "Peer Review Coordinator",
        "primaryGoal": "Manage physician peer review workflows including case assignment and tracking via M365 Copilot",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Coordinates peer review workflows using SharePoint document management. PII only (physician names, case IDs -- not patient health data). Agent Builder M365 workflow orchestration and SharePoint integration are ideal.",
        "alternativeConsidered": "Copilot Studio could handle workflow tracking, but Agent Builder M365 Copilot integration provides better document-centric workflow management.",
    },
    {
        "id": "hc-038",
        "useCaseName": "Consent Form Manager",
        "primaryGoal": "Generate procedure-specific consent forms and track patient consent status via Teams",
        "category": "Compliance & Quality",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Simple consent form generation from SharePoint templates via Teams. PII only (patient name, procedure type -- not health records). Copilot Studio excels at template-driven form generation with hard approval gates.",
        "alternativeConsidered": "Agent Builder could generate forms via M365 Copilot, but the Teams-first workflow with hard approval makes Copilot Studio more suitable.",
    },
    {
        "id": "hc-039",
        "useCaseName": "Medical Staff Credentialing Agent",
        "primaryGoal": "Automate physician credentialing verification and expiring certification tracking via M365 Copilot",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Tracks physician credentials from SharePoint document stores via M365 Copilot. PII only (physician names, license numbers). Agent Builder document management and M365 integration streamline credentialing workflows.",
        "alternativeConsidered": "Copilot Studio could handle reminders, but Agent Builder SharePoint document understanding and M365 workflow integration provide better credential management.",
    },
    {
        "id": "hc-040",
        "useCaseName": "Mortality & Morbidity Review Prep",
        "primaryGoal": "Prepare M&M conference cases by pulling de-identified clinical data and literature references from Fabric",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Analyzes de-identified case data in Fabric Lakehouse for M&M conference preparation. No PHI (all data is de-identified per M&M protocols). Fabric Agent excels at structured data analysis and literature cross-referencing.",
        "alternativeConsidered": "Foundry Agent could provide deeper analysis, but the de-identified data and read-only analytics pattern are well-served by Fabric Agent.",
    },
    # === 41-50: Operations & Workforce ===
    {
        "id": "hc-041",
        "useCaseName": "Staff Scheduling Optimizer",
        "primaryGoal": "Analyze staffing patterns and patient census data in Fabric to optimize nurse and physician schedules",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Staffing analytics across Fabric Lakehouse using employee PII (names, schedules, certifications -- not patient PHI). Fabric Agent data pipeline and analytics capabilities are ideal for workforce optimization.",
        "alternativeConsidered": "Foundry Agent could handle more complex autonomous scheduling, but the read-only analytics pattern with Fabric data makes Fabric Agent the better choice.",
    },
    {
        "id": "hc-042",
        "useCaseName": "Supply Chain Demand Forecaster",
        "primaryGoal": "Predict medical supply demand based on patient volume trends and seasonal patterns in Fabric",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Supply chain analytics using Fabric Lakehouse historical data. No patient or employee data involved. Fabric Agent time-series analysis and data pipeline capabilities are purpose-built for demand forecasting.",
        "alternativeConsidered": "Foundry Agent could host a custom forecasting model, but standard Fabric analytics suffice for this pattern.",
    },
    {
        "id": "hc-043",
        "useCaseName": "Bed Management Dashboard",
        "primaryGoal": "Track bed availability across units and analyze utilization trends using Fabric operational data",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["fabric", "azuresql"],
        "hasPhi": "pii",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Operational bed utilization analytics in Fabric. PII-level data (bed assignments use patient IDs, not health records). Fabric Agent real-time data capabilities and operational dashboarding are ideal.",
        "alternativeConsidered": "Foundry Agent could handle real-time bed tracking with more autonomy, but the analytics dashboard pattern with Fabric data makes Fabric Agent more efficient.",
    },
    {
        "id": "hc-044",
        "useCaseName": "Employee Onboarding Health Guide",
        "primaryGoal": "Guide new healthcare employees through compliance training and policy acknowledgments via Teams",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Simple guided Teams bot walking new employees through training checklists. No sensitive data (public training materials from SharePoint). Copilot Studio is the fastest path for this low-code onboarding workflow.",
        "alternativeConsidered": "Agent Builder could deliver this via M365 Copilot, but the Teams-first guided checklist pattern is Copilot Studio core strength.",
    },
    {
        "id": "hc-045",
        "useCaseName": "Equipment Maintenance Predictor",
        "primaryGoal": "Predict medical equipment maintenance needs from SharePoint maintenance logs and manufacturer guidelines via M365 Copilot",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Analyzes equipment maintenance documents in SharePoint via M365 Copilot. No patient or sensitive data. Agent Builder document grounding and M365 integration are ideal for maintenance scheduling from document analysis.",
        "alternativeConsidered": "Fabric Agent could analyze maintenance data at scale, but the SharePoint document-centric workflow favors Agent Builder.",
    },
    {
        "id": "hc-046",
        "useCaseName": "Multi-Site Performance Comparator",
        "primaryGoal": "Compare operational KPIs across hospital sites using Fabric and Snowflake data to identify best practices",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["fabric", "snowflake"],
        "hasPhi": "no",
        "uxChannel": "web",
        "codeCapability": "mixed",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Cross-site analytics combining Fabric Lakehouse and Snowflake data warehouses. No patient data (operational KPIs only). Fabric Agent dual data source support and analytics capabilities are purpose-built for this.",
        "alternativeConsidered": "Foundry Agent could handle Snowflake integration, but the analytics-first pattern with Fabric + Snowflake makes Fabric Agent the natural choice.",
    },
    {
        "id": "hc-047",
        "useCaseName": "Physician Burnout Early Warning",
        "primaryGoal": "Analyze physician workload data and engagement signals from HR documents via M365 Copilot",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Analyzes HR and workload documents in SharePoint via M365 Copilot. PII only (physician names, hours worked -- not patient data). Agent Builder document analysis and M365 integration support this HR analytics pattern.",
        "alternativeConsidered": "Fabric Agent could analyze workload data at scale, but the SharePoint HR document-centric analysis favors Agent Builder.",
    },
    {
        "id": "hc-048",
        "useCaseName": "Multi-Agent Claims Processing Pipeline",
        "primaryGoal": "Coordinate intake, coding, submission, and follow-up agents for end-to-end claims processing",
        "category": "Operations & Workforce",
        "complexity": "multiagent",
        "dataSources": ["azuresql", "external_api", "fabric"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "multiagent",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Multi-agent pipeline handling clinical documentation (PHI) across 4 specialized agents. Only Foundry supports multi-agent orchestration with PHI compliance at enterprise scale.",
        "alternativeConsidered": "No other architecture supports multi-agent orchestration with PHI compliance. Fabric Agent handles data but not multi-agent workflows.",
    },
    {
        "id": "hc-049",
        "useCaseName": "Patient Transport Coordinator",
        "primaryGoal": "Coordinate intra-hospital patient transport scheduling and staff assignment via Teams",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "pii",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Simple Teams bot for transport staff coordination. PII only (patient room numbers, transport staff names -- not health records). Copilot Studio excels at this guided Teams coordination workflow.",
        "alternativeConsidered": "Foundry Agent would be overkill for a simple transport coordination bot without PHI or complex orchestration needs.",
    },
    {
        "id": "hc-050",
        "useCaseName": "Clinical Research Data Harmonizer",
        "primaryGoal": "Harmonize clinical data from multiple EMR systems into standardized FHIR format for research",
        "category": "Operations & Workforce",
        "complexity": "complex",
        "dataSources": ["azuresql", "external_api", "snowflake"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "byom",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Autonomous data harmonization across EMR systems (PHI) using a custom FHIR mapping model (BYOM). Triple requirement: PHI compliance, custom model, and autonomous multi-system orchestration -- only Foundry can deliver all three.",
        "alternativeConsidered": "Fabric Agent could handle data harmonization for non-PHI data, but the PHI, BYOM, and autonomous requirements all mandate Foundry.",
    },
]
