"""
50 predefined healthcare provider use cases for the Architecture Advisor dashboard.
Distribution: 13 Copilot Studio / 12 Agent Builder / 12 Fabric Agent / 13 Foundry Agent
"""

HEALTHCARE_CASES = [
    {
        "id": "hc-001",
        "useCaseName": "Patient FAQ Chatbot",
        "primaryGoal": "Answer common patient questions about office hours, insurance accepted, and appointment prep instructions via Teams",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Simple Q&A pattern with SharePoint knowledge base delivered through Teams. Copilot Studio excels at low-code conversational agents grounded in SharePoint content (Microsoft Learn: Copilot Studio reference architectures). No PHI, no custom models, no complex orchestration needed.",
        "alternativeConsidered": "Agent Builder was considered but the use case doesn't require M365 Copilot embedding — a standalone Teams bot is more appropriate for a patient-facing FAQ.",
    },
    {
        "id": "hc-002",
        "useCaseName": "Staff Onboarding Assistant",
        "primaryGoal": "Guide new clinical staff through onboarding checklists, policy acknowledgments, and training module completion via Teams",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Guided multi-step onboarding workflow in Teams with hard approval gates (manager sign-off). Copilot Studio's Power Automate integration handles approval flows natively (Microsoft Learn: Healthcare Patient Support Agent pattern). No PHI involved — standard HR/training content.",
        "alternativeConsidered": "Foundry Agent would be over-engineered for a simple onboarding checklist with no PHI or custom model requirements.",
    },
    {
        "id": "hc-003",
        "useCaseName": "Appointment Scheduling Bot",
        "primaryGoal": "Help patients schedule, reschedule, or cancel appointments through a conversational Teams interface",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["none"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Conversational appointment management in Teams using Copilot Studio's built-in dialog flows and Dataverse integration (Microsoft Learn: Intelligent cardiac triage pattern). Simple guided workflow with inline confirmation — no complex orchestration needed.",
        "alternativeConsidered": "Agent Builder was considered but M365 Copilot embedding isn't needed — patients interact through a dedicated Teams bot, not within the Copilot experience.",
    },
    {
        "id": "hc-004",
        "useCaseName": "Benefits Inquiry Assistant",
        "primaryGoal": "Answer employee questions about health benefits, PTO policies, and enrollment deadlines via Teams chat",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Read-only Q&A grounded in SharePoint HR policy documents, delivered through Teams. Copilot Studio's topic-based authoring is ideal for structured FAQ with escalation to HR staff when questions exceed scope (Microsoft Learn: Copilot Studio reference architectures).",
        "alternativeConsidered": "No alternative needed — this is a textbook Copilot Studio pattern: simple, low-code, Teams-based, SharePoint-grounded FAQ bot.",
    },
    {
        "id": "hc-005",
        "useCaseName": "Prescription Refill Request Bot",
        "primaryGoal": "Allow patients to request prescription refills through a guided Teams conversation with pharmacist approval",
        "category": "Clinical Operations",
        "complexity": "moderate",
        "dataSources": ["none"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Guided refill workflow with hard approval gate (pharmacist must approve). Copilot Studio's Power Automate connector triggers approval flows natively. No PHI in the bot conversation itself — refill requests reference medication names only, with pharmacist verifying in the EHR separately.",
        "alternativeConsidered": "Foundry was considered due to pharmacy domain complexity, but the bot only collects refill requests without accessing PHI data — the pharmacist handles verification in a separate HIPAA-compliant system.",
    },
    {
        "id": "hc-006",
        "useCaseName": "Visitor Check-In Kiosk Agent",
        "primaryGoal": "Guide hospital visitors through check-in, badge printing, and wayfinding via a Teams-connected kiosk interface",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["none"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Simple guided workflow for visitor check-in. Copilot Studio's adaptive card support enables rich kiosk-style interactions in Teams. No PHI, no complex integrations — just a step-by-step dialog flow with inline confirmation.",
        "alternativeConsidered": "Agent Builder was considered but the kiosk operates standalone, not embedded in the M365 Copilot experience.",
    },
    {
        "id": "hc-007",
        "useCaseName": "Clinical Policy Lookup Agent",
        "primaryGoal": "Help clinicians quickly find relevant clinical policies, procedures, and guidelines from the hospital's SharePoint knowledge base",
        "category": "Compliance & Quality",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Read-only knowledge retrieval from SharePoint policy library via Teams. Copilot Studio's SharePoint connector enables semantic search over documents without custom code (Microsoft Learn: Copilot Studio reference architectures). No PHI — policies are organizational documents.",
        "alternativeConsidered": "Agent Builder could work here but the use case doesn't need M365 Copilot integration — a dedicated Teams bot is simpler and more discoverable for clinical staff.",
    },
    {
        "id": "hc-008",
        "useCaseName": "IT Helpdesk Triage Bot",
        "primaryGoal": "Triage IT support requests from clinical staff, resolve common issues automatically, and escalate complex tickets to ServiceNow",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["servicenow"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "IT triage pattern with ServiceNow integration via Power Automate connectors. Copilot Studio's topic-based routing handles common issues (password resets, VPN, badge access) and escalates to ServiceNow for complex tickets. No PHI — IT support data only.",
        "alternativeConsidered": "Foundry was considered for ServiceNow integration but Copilot Studio's pre-built ServiceNow connector handles this without custom code.",
    },
    {
        "id": "hc-009",
        "useCaseName": "Patient Satisfaction Survey Bot",
        "primaryGoal": "Collect post-visit patient satisfaction feedback through a conversational Teams survey with real-time sentiment tracking",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["none"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Simple survey collection bot in Teams. Copilot Studio's dialog management and Dataverse integration store responses for Power BI dashboards. No PHI — satisfaction scores and free-text feedback only.",
        "alternativeConsidered": "A simple Forms/Power Automate flow was considered but the conversational interface improves response rates compared to static surveys.",
    },
    {
        "id": "hc-010",
        "useCaseName": "Nurse Shift Swap Coordinator",
        "primaryGoal": "Enable nurses to request and approve shift swaps through a Teams bot with manager approval workflow",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "hard",
        "whyThisArchitecture": "Guided workflow with hard approval gate (manager must approve swaps). Copilot Studio's Teams Adaptive Cards and Power Automate approval connector handle the multi-step swap request, availability check, and manager sign-off natively.",
        "alternativeConsidered": "Power Automate alone could handle this but the conversational interface makes it easier for nurses to initiate swaps during busy shifts without navigating a portal.",
    },
    {
        "id": "hc-011",
        "useCaseName": "Facility Maintenance Request Bot",
        "primaryGoal": "Allow staff to report facility issues (broken equipment, HVAC, cleaning) through Teams with auto-routing to the correct maintenance team",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["none"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Simple issue-reporting workflow with category-based routing. Copilot Studio's topic routing directs requests to the correct team (biomedical, HVAC, environmental services) and creates Dataverse tickets automatically.",
        "alternativeConsidered": "ServiceNow integration was considered but the hospital uses Dataverse for work orders, making Copilot Studio the natural fit.",
    },
    {
        "id": "hc-012",
        "useCaseName": "Compliance Training Tracker",
        "primaryGoal": "Track and remind clinical staff about required compliance training completions (HIPAA, safety, infection control) through Teams notifications",
        "category": "Compliance & Quality",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Read-only training status lookup with proactive reminders. Copilot Studio's scheduled Power Automate flows send Teams notifications for overdue training. Staff can check their status via Teams chat. No PHI — training records only.",
        "alternativeConsidered": "A standalone Power Automate flow could send reminders, but the conversational interface lets staff check status on-demand and acknowledge completions inline.",
    },
    {
        "id": "hc-013",
        "useCaseName": "Cafeteria Menu & Dietary Bot",
        "primaryGoal": "Provide daily cafeteria menus with dietary filtering (vegan, gluten-free, allergen alerts) to staff and patients via Teams",
        "category": "Patient Engagement",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "teams",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "small",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Simple read-only lookup of daily menus stored in SharePoint lists with dietary filtering. Copilot Studio's SharePoint connector and topic-based dialog handle filtering by dietary preference. Trivial complexity, no PHI.",
        "alternativeConsidered": "A SharePoint page with Power Apps was considered but the Teams bot provides faster access during busy shifts without navigating to a portal.",
    },
    {
        "id": "hc-014",
        "useCaseName": "Clinical Document Summarizer",
        "primaryGoal": "Summarize lengthy clinical guidelines, research papers, and policy documents directly within the M365 Copilot experience",
        "category": "Clinical Operations",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Declarative agent pattern in M365 Copilot with SharePoint grounding. Agent Builder enables natural language document summarization over clinical guidelines stored in SharePoint (Microsoft Learn: Declarative agent best practices). No PHI — organizational knowledge documents only.",
        "alternativeConsidered": "Copilot Studio was considered but the use case benefits from M365 Copilot's native document understanding and inline experience — users don't leave their workflow.",
    },
    {
        "id": "hc-015",
        "useCaseName": "Meeting Notes & Action Item Extractor",
        "primaryGoal": "Automatically extract action items, decisions, and follow-ups from clinical committee meeting transcripts in M365 Copilot",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "M365 Copilot declarative agent grounded in Teams meeting transcripts and SharePoint. Agent Builder's native integration with Microsoft Graph enables access to meeting notes, transcripts, and documents (Microsoft Learn: Add knowledge sources to declarative agents).",
        "alternativeConsidered": "Copilot Studio could build a similar bot but would lose the seamless M365 Copilot inline experience and native Graph connector access.",
    },
    {
        "id": "hc-016",
        "useCaseName": "HR Policy Advisor (M365 Copilot)",
        "primaryGoal": "Answer HR policy questions with citations from the employee handbook and policy documents within M365 Copilot",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Declarative agent with SharePoint grounding for HR policy Q&A. Agent Builder is the optimal choice when users are already in M365 Copilot and need grounded answers from SharePoint document libraries (Microsoft Learn: Choose the right tool for declarative agents).",
        "alternativeConsidered": "Copilot Studio could deliver similar functionality but users prefer staying in the M365 Copilot experience rather than switching to a separate Teams bot.",
    },
    {
        "id": "hc-017",
        "useCaseName": "Contract Review Assistant",
        "primaryGoal": "Help legal and procurement teams review vendor contracts, flag key terms, and compare against standard templates within M365 Copilot",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Document comparison and term extraction pattern using M365 Copilot's native document understanding. Agent Builder's SharePoint grounding enables cross-referencing contracts against templates stored in document libraries (Microsoft Learn: Best practices for declarative agents).",
        "alternativeConsidered": "Foundry was considered for its advanced NLP but the use case doesn't involve PHI, custom models, or complex orchestration — M365 Copilot's built-in capabilities suffice.",
    },
    {
        "id": "hc-018",
        "useCaseName": "Research Literature Navigator",
        "primaryGoal": "Help clinical researchers find and summarize relevant medical literature and internal research documents via M365 Copilot",
        "category": "Clinical Operations",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Knowledge retrieval agent grounded in SharePoint research library. Agent Builder enables researchers to query their document corpus in natural language within M365 Copilot without leaving their workflow (Microsoft Learn: Add knowledge sources to declarative agents).",
        "alternativeConsidered": "Azure AI Search + Foundry could provide more advanced semantic search but the volume and complexity don't justify the infrastructure — SharePoint grounding handles this well.",
    },
    {
        "id": "hc-019",
        "useCaseName": "Quality Metrics Report Generator",
        "primaryGoal": "Generate quality metrics summaries and reports from SharePoint-stored quality data within the M365 Copilot experience",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Report generation pattern using M365 Copilot's document synthesis capabilities. Agent Builder declarative agent grounded in SharePoint quality data lists and Excel workbooks, generating formatted summaries on demand.",
        "alternativeConsidered": "Fabric Agent was considered for analytics but the data lives in SharePoint lists/Excel, not in a Fabric Lakehouse — Agent Builder is the natural fit.",
    },
    {
        "id": "hc-020",
        "useCaseName": "Credential Verification Lookup",
        "primaryGoal": "Help HR verify staff credentials, licenses, and certifications by searching credential documents stored in SharePoint via M365 Copilot",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Document search and verification pattern using Agent Builder's SharePoint grounding. HR staff query credential documents within M365 Copilot — no PHI, just professional licenses and certifications.",
        "alternativeConsidered": "A PowerApps portal was considered but the M365 Copilot inline experience is faster for ad-hoc credential lookups during hiring.",
    },
    {
        "id": "hc-021",
        "useCaseName": "Grant Proposal Assistant",
        "primaryGoal": "Help research teams draft grant proposals by pulling relevant prior work, budgets, and templates from SharePoint within M365 Copilot",
        "category": "Operations & Workforce",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Document synthesis and guided drafting pattern. Agent Builder's M365 Copilot integration lets researchers pull templates, prior proposals, and budget data from SharePoint while drafting directly in Word (Microsoft Learn: Best practices for declarative agents).",
        "alternativeConsidered": "Copilot Studio could provide similar functionality but researchers strongly prefer the M365 Copilot inline experience while working in Word and Excel.",
    },
    {
        "id": "hc-022",
        "useCaseName": "Vendor Compliance Checker",
        "primaryGoal": "Check vendor compliance documentation against regulatory requirements using SharePoint-stored checklists within M365 Copilot",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Compliance document cross-referencing pattern. Agent Builder enables comparison of vendor submissions against regulatory checklists stored in SharePoint, with M365 Copilot providing citations and highlighting gaps.",
        "alternativeConsidered": "Foundry was considered but the regulatory checklists are structured documents in SharePoint — no PHI, no custom models needed.",
    },
    {
        "id": "hc-023",
        "useCaseName": "Training Material Finder",
        "primaryGoal": "Help staff discover relevant training materials, SOPs, and instructional videos from the SharePoint learning library via M365 Copilot",
        "category": "Operations & Workforce",
        "complexity": "simple",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Content discovery agent using Agent Builder's SharePoint grounding. Staff search for training materials in natural language within M365 Copilot, getting direct links and summaries of relevant SOPs and videos.",
        "alternativeConsidered": "A SharePoint search page exists but the M365 Copilot conversational interface provides better natural language understanding for finding specific training topics.",
    },
    {
        "id": "hc-024",
        "useCaseName": "Incident Report Drafter",
        "primaryGoal": "Help safety officers draft incident reports by pulling templates and prior incident data from SharePoint within M365 Copilot",
        "category": "Compliance & Quality",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "guided",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Guided document drafting pattern using M365 Copilot inline experience. Agent Builder pulls incident report templates and prior cases from SharePoint, helping safety officers draft standardized reports without leaving Word.",
        "alternativeConsidered": "Copilot Studio could collect incident data via Teams forms but the drafting experience is better in M365 Copilot where the report is being written.",
    },
    {
        "id": "hc-025",
        "useCaseName": "Department Budget Analyst",
        "primaryGoal": "Answer budget questions by analyzing departmental financial spreadsheets and reports stored in SharePoint via M365 Copilot",
        "category": "Revenue Cycle",
        "complexity": "moderate",
        "dataSources": ["sharepoint"],
        "hasPhi": "no",
        "uxChannel": "m365copilot",
        "codeCapability": "lowcode",
        "userVolume": "small",
        "realtime": "no",
        "teamSize": "medium",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Financial document analysis pattern using M365 Copilot's Excel and document understanding. Agent Builder declarative agent grounded in SharePoint financial reports and Excel workbooks for natural language budget queries.",
        "alternativeConsidered": "Fabric Agent was considered for analytics but the data is in SharePoint Excel files, not a Fabric Lakehouse — Agent Builder handles this without data pipeline setup.",
    },
    {
        "id": "hc-026",
        "useCaseName": "Revenue Cycle Analytics Dashboard",
        "primaryGoal": "Analyze revenue cycle metrics (denial rates, days in A/R, collection rates) across departments using Fabric Lakehouse data",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Data-centric analytics pattern on Microsoft Fabric + OneLake. Fabric Data Agent enables conversational Q&A over lakehouse data using natural language (Microsoft Learn: Fabric data agent concepts). Financial data in Fabric Lakehouse requires the Fabric Agent for native OneLake access and semantic model integration.",
        "alternativeConsidered": "Foundry was considered but there's no PHI in aggregated revenue metrics — financial data compliance is handled by Fabric's security controls. Fabric Agent provides direct lakehouse access without additional infrastructure.",
    },
    {
        "id": "hc-027",
        "useCaseName": "Supply Chain Cost Optimizer",
        "primaryGoal": "Analyze medical supply procurement costs, vendor pricing, and inventory levels from Snowflake warehouse to identify savings opportunities",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["snowflake", "fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Multi-source analytics pattern combining Snowflake warehouse data with Fabric Lakehouse. Fabric Agent's native Snowflake connector and OneLake integration enable cross-platform supply chain analysis (Microsoft Learn: Fabric data agent with Lakehouse). Financial procurement data — no PHI involved.",
        "alternativeConsidered": "Foundry was considered but there's no PHI, no custom models, and no autonomous behavior needed. Fabric Agent handles multi-source analytics natively.",
    },
    {
        "id": "hc-028",
        "useCaseName": "Patient Volume Forecasting",
        "primaryGoal": "Forecast patient admission volumes by department and season using historical Fabric Lakehouse data for capacity planning",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Time-series analytics pattern on Fabric Lakehouse. Fabric Data Agent enables natural language queries over historical admission data and forecasting models stored in OneLake (Microsoft Learn: Fabric data agent scenario with AdventureWorks). Aggregated volume data — no individual PHI.",
        "alternativeConsidered": "Foundry was considered for ML-based forecasting but Fabric's built-in ML capabilities and Data Agent handle this pattern without requiring separate AI infrastructure.",
    },
    {
        "id": "hc-029",
        "useCaseName": "Claims Denial Pattern Analyzer",
        "primaryGoal": "Identify patterns in insurance claim denials by analyzing denial codes, payer trends, and appeal outcomes from Fabric Lakehouse",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Pattern analysis over structured financial data in Fabric Lakehouse. Fabric Data Agent enables conversational analytics over denial code distributions, payer-specific patterns, and trending (Microsoft Learn: Semantic model best practices for data agent). Financial claims data — aggregated, no individual PHI.",
        "alternativeConsidered": "Foundry was considered for advanced ML but the pattern analysis is primarily SQL-based aggregation over structured data — Fabric Agent handles this more efficiently.",
    },
    {
        "id": "hc-030",
        "useCaseName": "Operational KPI Monitor",
        "primaryGoal": "Monitor and report on operational KPIs (bed occupancy, ER wait times, OR utilization) from Fabric Lakehouse data in real-time dashboards",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Real-time KPI monitoring pattern using Fabric's streaming analytics and Data Agent. Fabric Agent provides conversational access to live operational metrics stored in OneLake, with Power BI integration for visualization (Microsoft Learn: Fabric data agent concepts). Aggregated operational metrics — no individual PHI.",
        "alternativeConsidered": "Foundry was considered for real-time processing but Fabric's native streaming and KQL capabilities handle operational KPI monitoring without additional infrastructure.",
    },
    {
        "id": "hc-031",
        "useCaseName": "Staffing Cost Analyzer",
        "primaryGoal": "Analyze staffing costs, overtime trends, and labor productivity metrics across departments using Snowflake data",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["snowflake"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Financial analytics pattern on Snowflake data warehouse. Fabric Agent's Snowflake connector enables conversational access to staffing cost data without migrating to OneLake (Microsoft Learn: Fabric data agent creation). Financial labor data — no PHI.",
        "alternativeConsidered": "Agent Builder was considered but the data lives in Snowflake, not SharePoint — Fabric Agent provides the native data warehouse connectivity needed.",
    },
    {
        "id": "hc-032",
        "useCaseName": "Population Health Trend Analyzer",
        "primaryGoal": "Analyze de-identified population health trends (chronic disease prevalence, vaccination rates, demographic patterns) from Fabric Lakehouse",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Population-level analytics pattern on de-identified datasets in Fabric Lakehouse. Fabric Data Agent enables epidemiologists to query trends in natural language (Microsoft Learn: Fabric data agent scenario). Data is de-identified and aggregated — no individual PHI present.",
        "alternativeConsidered": "Foundry was considered for advanced ML models but the analytics are primarily SQL-based trend analysis over pre-aggregated data — Fabric Agent handles this more efficiently.",
    },
    {
        "id": "hc-033",
        "useCaseName": "Equipment Utilization Tracker",
        "primaryGoal": "Track and analyze medical equipment utilization rates, maintenance schedules, and replacement forecasts from Fabric Lakehouse data",
        "category": "Operations & Workforce",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Asset management analytics pattern using Fabric Lakehouse. Fabric Data Agent enables natural language queries over equipment telemetry and maintenance data stored in OneLake. Financial asset data — no PHI.",
        "alternativeConsidered": "A standalone Power BI dashboard exists but the conversational agent enables ad-hoc queries that aren't covered by pre-built reports.",
    },
    {
        "id": "hc-034",
        "useCaseName": "Payer Mix Optimization Analyzer",
        "primaryGoal": "Analyze payer mix distribution, reimbursement rates, and contract performance across service lines using Snowflake and Fabric data",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["snowflake", "fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Multi-source financial analytics combining Snowflake (payer contracts) and Fabric Lakehouse (claims data). Fabric Agent's dual-source connectivity enables cross-platform payer analysis without data migration (Microsoft Learn: Fabric data agent with multiple sources).",
        "alternativeConsidered": "Foundry was considered for advanced analytics but the pattern is primarily SQL-based financial aggregation — Fabric Agent handles cross-source joins natively.",
    },
    {
        "id": "hc-035",
        "useCaseName": "Clinical Trial Enrollment Analytics",
        "primaryGoal": "Analyze clinical trial enrollment rates, screening-to-enrollment conversion, and site performance metrics from Fabric Lakehouse",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Trial analytics pattern on de-identified enrollment metrics in Fabric Lakehouse. Fabric Data Agent enables natural language queries over trial performance data (enrollment rates, conversion funnels, site comparisons). Aggregated trial metrics — no individual PHI.",
        "alternativeConsidered": "Foundry was considered for ML-based enrollment prediction but the current need is descriptive analytics over structured data — Fabric Agent is more efficient.",
    },
    {
        "id": "hc-036",
        "useCaseName": "Energy & Sustainability Monitor",
        "primaryGoal": "Track hospital energy consumption, carbon footprint, and sustainability metrics from IoT sensor data in Fabric Lakehouse",
        "category": "Operations & Workforce",
        "complexity": "complex",
        "dataSources": ["fabric"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "IoT analytics pattern using Fabric's real-time streaming and Data Agent. Energy consumption and sustainability metrics from building sensors flow into OneLake for trend analysis and anomaly detection. No PHI — facility operations data only.",
        "alternativeConsidered": "Azure IoT Hub + Foundry was considered but Fabric's native streaming analytics and Data Agent provide the end-to-end pipeline without additional infrastructure.",
    },
    {
        "id": "hc-037",
        "useCaseName": "Pharmacy Inventory Optimizer",
        "primaryGoal": "Optimize pharmacy inventory levels by analyzing dispensing patterns, expiration rates, and reorder points from Snowflake warehouse data",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["snowflake"],
        "hasPhi": "financial",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "readonly",
        "customModel": "no",
        "humanInLoop": "no",
        "whyThisArchitecture": "Inventory analytics pattern on Snowflake data warehouse. Fabric Agent's Snowflake connector enables conversational analysis of dispensing patterns, stock levels, and reorder optimization. Financial inventory data — no individual PHI.",
        "alternativeConsidered": "Foundry was considered for predictive restocking models but the current need is descriptive analytics and threshold-based alerts — Fabric Agent handles this without ML infrastructure.",
    },
    {
        "id": "hc-038",
        "useCaseName": "Patient Discharge Summary Generator",
        "primaryGoal": "Automatically generate HIPAA-compliant discharge summaries from clinical notes, lab results, and medication lists",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "PHI/HIPAA compliance is a hard requirement — only Azure AI Foundry provides the BAA coverage and audit controls needed for processing clinical notes with Protected Health Information (Microsoft Learn: Foundry Agent Service overview). Autonomous document generation from PHI data requires Foundry's compliance boundary and content safety controls.",
        "alternativeConsidered": "Copilot Studio and Agent Builder cannot process PHI data. Fabric Agent lacks the compliance controls needed for clinical document generation with patient data.",
    },
    {
        "id": "hc-039",
        "useCaseName": "Clinical Decision Support Agent",
        "primaryGoal": "Provide real-time clinical decision support by analyzing patient vitals, lab results, and medication interactions with PHI compliance",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "PHI/HIPAA compliance required for accessing patient vitals and lab results. Real-time clinical decision support with autonomous action recommendations requires Foundry's compliance boundary, content safety, and low-latency processing (Microsoft Learn: Foundry Agent Service standard setup). Only Foundry provides the BAA coverage needed.",
        "alternativeConsidered": "All non-Foundry architectures are blocked by PHI hard-cap enforcement. Patient clinical data cannot be processed outside the Foundry compliance boundary.",
    },
    {
        "id": "hc-040",
        "useCaseName": "Multi-Agent Care Coordinator",
        "primaryGoal": "Orchestrate multiple specialized agents (scheduling, medication, referral, follow-up) to coordinate patient care across departments",
        "category": "Clinical Operations",
        "complexity": "multiagent",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "multiagent",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Multi-agent orchestration with PHI data requires Azure AI Foundry's connected agents capability (Microsoft Learn: Build collaborative multi-agent systems with Connected Agents). Each sub-agent handles a specific care coordination task while the primary agent manages routing. PHI compliance + multi-agent = Foundry only.",
        "alternativeConsidered": "No alternative supports both multi-agent orchestration AND PHI/HIPAA compliance. Copilot Studio and Agent Builder lack multi-agent capabilities; Fabric Agent lacks PHI compliance.",
    },
    {
        "id": "hc-041",
        "useCaseName": "Radiology Report Analyzer",
        "primaryGoal": "Analyze radiology reports to flag critical findings, suggest follow-up imaging, and prioritize radiologist review queue",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "PHI/HIPAA compliance required for radiology reports containing patient data. Autonomous prioritization of critical findings requires Foundry's content safety and audit controls. API integration with PACS/RIS systems requires Foundry's enterprise connectivity (Microsoft Learn: Baseline Foundry Chat Reference Architecture).",
        "alternativeConsidered": "All non-Foundry architectures are blocked by PHI hard-cap. Radiology reports contain Protected Health Information that cannot be processed outside Foundry's compliance boundary.",
    },
    {
        "id": "hc-042",
        "useCaseName": "Clinical Trial Patient Matcher",
        "primaryGoal": "Match patients to active clinical trials based on diagnosis, demographics, and lab values with PHI-compliant processing",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "medium",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "PHI/HIPAA compliance required — matching patients to trials requires accessing diagnosis codes, lab values, and demographics (all PHI). Foundry's BAA coverage and audit trail ensure compliant patient-trial matching (Microsoft Learn: Foundry Agent Service overview). Autonomous matching with clinician review.",
        "alternativeConsidered": "All non-Foundry architectures are blocked by PHI hard-cap. Patient matching requires access to Protected Health Information that cannot leave the Foundry compliance boundary.",
    },
    {
        "id": "hc-043",
        "useCaseName": "Medication Interaction Checker",
        "primaryGoal": "Autonomously check prescribed medications against patient's current medication list and flag dangerous interactions in real-time",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "PHI/HIPAA compliance required for accessing patient medication lists. Real-time autonomous interaction checking with patient data requires Foundry's compliance boundary and content safety controls. API integration with EHR/pharmacy systems (Microsoft Learn: Foundry Agent Service standard setup).",
        "alternativeConsidered": "All non-Foundry architectures are blocked by PHI hard-cap. Medication data is Protected Health Information requiring Foundry's BAA coverage.",
    },
    {
        "id": "hc-044",
        "useCaseName": "Prior Authorization Automation Agent",
        "primaryGoal": "Automate insurance prior authorization submissions by extracting clinical justification from patient records and submitting to payers",
        "category": "Revenue Cycle",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "PHI/HIPAA compliance required — prior auth requires extracting clinical data from patient records. Autonomous submission to payer portals requires Foundry's enterprise API connectivity and compliance controls. Only Foundry can process PHI while taking autonomous external actions (Microsoft Learn: Foundry Agent Service overview).",
        "alternativeConsidered": "Copilot Studio could handle simple form-filling but cannot access PHI data or make autonomous payer API submissions. Foundry's compliance boundary is required.",
    },
    {
        "id": "hc-045",
        "useCaseName": "Sepsis Early Warning System",
        "primaryGoal": "Monitor patient vitals in real-time and autonomously alert care teams when sepsis risk indicators are detected",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "PHI/HIPAA compliance required for real-time patient vital monitoring. Autonomous alerting based on clinical indicators requires Foundry's content safety and audit controls. Enterprise-scale real-time processing of PHI data (Microsoft Learn: Baseline Foundry Chat Reference Architecture).",
        "alternativeConsidered": "All non-Foundry architectures are blocked by PHI hard-cap. Real-time patient monitoring data is Protected Health Information requiring Foundry's compliance boundary.",
    },
    {
        "id": "hc-046",
        "useCaseName": "Multi-Agent Revenue Integrity Auditor",
        "primaryGoal": "Orchestrate coding, billing, and compliance agents to audit charge capture accuracy and identify revenue leakage with PHI access",
        "category": "Revenue Cycle",
        "complexity": "multiagent",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "multiagent",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Multi-agent orchestration with PHI data. Coding agent validates CPT/ICD codes, billing agent checks charge capture, compliance agent flags audit risks. Foundry's Connected Agents feature enables this coordination (Microsoft Learn: Connected Agents in Foundry). PHI + multi-agent = Foundry only.",
        "alternativeConsidered": "No alternative supports both multi-agent orchestration AND PHI compliance. Each sub-agent needs access to patient billing records containing PHI.",
    },
    {
        "id": "hc-047",
        "useCaseName": "Pathology Report NLP Extractor",
        "primaryGoal": "Extract structured data (tumor staging, margins, biomarkers) from unstructured pathology reports using fine-tuned clinical NLP models",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "finetune",
        "humanInLoop": "soft",
        "whyThisArchitecture": "Triple requirement: PHI/HIPAA compliance + fine-tuned clinical NLP model + autonomous extraction. Only Azure AI Foundry supports all three: BAA coverage for pathology data, custom model hosting for domain-specific NLP, and autonomous processing pipeline (Microsoft Learn: Foundry Agent Service overview). Fine-tuned model deployment requires Foundry infrastructure.",
        "alternativeConsidered": "No alternative supports fine-tuned model deployment. Additionally, pathology reports contain PHI, which blocks all non-Foundry architectures via hard-cap enforcement.",
    },
    {
        "id": "hc-048",
        "useCaseName": "Patient Risk Stratification Engine",
        "primaryGoal": "Stratify patients by readmission risk using clinical history, social determinants, and lab trends with PHI-compliant ML models",
        "category": "Clinical Operations",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "soft",
        "whyThisArchitecture": "PHI/HIPAA compliance required for patient-level risk stratification using clinical history and social determinants. Enterprise-scale ML inference with autonomous risk scoring requires Foundry's compliance boundary and model hosting (Microsoft Learn: Baseline Foundry Chat Reference Architecture).",
        "alternativeConsidered": "All non-Foundry architectures are blocked by PHI hard-cap. Patient clinical history is Protected Health Information requiring Foundry's BAA coverage.",
    },
    {
        "id": "hc-049",
        "useCaseName": "Multi-Agent Referral Coordinator",
        "primaryGoal": "Orchestrate intake, eligibility, scheduling, and notification agents to automate the specialist referral process end-to-end with PHI",
        "category": "Clinical Operations",
        "complexity": "multiagent",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "web",
        "codeCapability": "procode",
        "userVolume": "large",
        "realtime": "no",
        "teamSize": "large",
        "agentBehavior": "multiagent",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "Multi-agent orchestration with PHI data for referral management. Intake agent processes referral, eligibility agent checks insurance, scheduling agent finds slots, notification agent confirms. Foundry's Connected Agents enables this pipeline (Microsoft Learn: Connected Agents in Foundry). PHI + multi-agent = Foundry only.",
        "alternativeConsidered": "Copilot Studio could handle simple referral forms but cannot orchestrate multiple agents or process PHI data. Foundry is required for both capabilities.",
    },
    {
        "id": "hc-050",
        "useCaseName": "Adverse Event Detection & Reporting",
        "primaryGoal": "Autonomously monitor clinical data streams for adverse events, classify severity, and generate FDA-compliant reports with PHI data",
        "category": "Compliance & Quality",
        "complexity": "complex",
        "dataSources": ["azuresql"],
        "hasPhi": "yes",
        "uxChannel": "api",
        "codeCapability": "procode",
        "userVolume": "enterprise",
        "realtime": "yes",
        "teamSize": "large",
        "agentBehavior": "autonomous",
        "customModel": "no",
        "humanInLoop": "escalation",
        "whyThisArchitecture": "PHI/HIPAA compliance required for clinical adverse event monitoring. Autonomous detection and FDA reporting from patient data streams requires Foundry's compliance boundary, content safety, and enterprise API connectivity (Microsoft Learn: Foundry Agent Service standard setup). Real-time processing of PHI clinical data.",
        "alternativeConsidered": "All non-Foundry architectures are blocked by PHI hard-cap. Adverse event data contains Protected Health Information and requires Foundry's audit trail for FDA reporting.",
    },
]
